name = "Highway"
license = "MIT"
licenselink = "https://github.com/ashishlahoti/hugo-theme-highway/blob/master/LICENSE.md"
description = "Highway is a responsive, clean and content-focused Hugo theme."
homepage = "https://github.com/ashishlahoti/hugo-theme-highway/"
tags = ["blog", "responsive", "customizable", "widgets", "rss", "disqus", "google analytics", "wordpress"]
features = ["blog", "responsive", "widgets", "shortcodes", "rss", "disqus"]
min_version = "0.48.0"

[author]
  name = "Ashish Lahoti"
  homepage = "https://github.com/ashishlahoti"
  