baseURL = "https://example.com/"
languageCode = "en-us"
title = "Hugo Highway Theme"
disqusShortname = "hugohighwaytheme" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "UA-XXXXXXXXX-X" # Enable Google Analytics by entering your tracking id
publishDir = "" # Directory of the generated Hugo website
assetDir = "static"
theme = "hugo-theme-highway"
themesdir = "../.."

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "section"
    name = "Section"
    url = "/section"
    weight = 2
  [[menu.main]]
    identifier = "category1"
    name = "Category1"
    url = "/categories/category1/"
    parent = "section"
    weight = 1
  [[menu.main]]
    identifier = "category2"
    name = "Category2"
    url = "/categories/category2/"
    parent = "section"
    weight = 2
  [[menu.main]]
    identifier = "category3"
    name = "Category3"
    url = "/categories/category3/"
    parent = "section"
    weight = 3
  [[menu.main]]
    identifier = "another-section"
    name = "Another Section"
    url = "/anothersection/"
    weight = 3
  [[menu.main]]
    identifier = "another-category1"
    name = "Another Category1"
    url = "/categories/anothercategory1/"
    parent = "another-section"
    weight = 1
  [[menu.main]]
    identifier = "another-category2"
    name = "Another Category2"
    url = "/categories/anothercategory2/"
    parent = "another-section"
    weight = 2  

[Author] # Default Author
  code = "ashishlahoti"
  name = "Ashish Lahoti"

[Params]
  title = "HugoHighwayTheme"
  subtitle = "Hugo blog made with love" # Subtitle of your site. Used in site header
  description = "This is a technical blog made with Hugo Highway Theme" # Site description. Used in meta description
  logo = "/img/favicon.ico"
  copyright = "HugoHighwayTheme" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["section", "anothersection"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "January 02, 2006" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#e22d30" # Override highlight color
  googleAdsense = "ca-pub-XXXXXXXXXXXXX" # Enable Google Adsense by entering ad client id
  blog_post = true # Show blog post meta such as author, date and categaory in the post header
  
[Params.social.share]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = true
  email = true

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  search = "right"
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "social", "categories", "taglist", "recent", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget
  categories_counter = true # Enable counter for each tag in "Categories" widget

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "username"
  instagram = "username"
  twitter = "@twitter_handle"
  linkedin = "username"
  telegram = "username"
  github = "username"
  gitlab = "username"
  bitbucket = "username"
  email = "abc@xyz.com"
  buymeacoffee = "username"

[[Params.widgets.social.custom]]
  title = "Home Page"
  url = "http://example.com/"

[markup]
  [markup.goldmark.renderer]
    unsafe= true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "index"
